name: first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  pdf: ^3.10.4
  csv: ^5.1.1
  share_plus: ^7.1.0
  intl: ^0.18.1
  permission_handler: ^10.4.3  # For Android permissions

  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^0.13.6
  dio: ^5.3.2
  dio_cookie_manager: ^2.0.1
  cookie_jar: ^3.0.1
  flutter_secure_storage: ^9.0.0

flutter:
  uses-material-design: true
