name: first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  pdf: ^3.10.4
  csv: ^6.0.0
  share_plus: ^10.1.4
  intl: ^0.20.2
  permission_handler: ^11.4.0  # For Android permissions

  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  file_picker: ^10.0.0
  flex_color_scheme: ^8.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  http: ^1.3.0
  dio: ^5.3.2
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^9.0.0

flutter:
  uses-material-design: true
